openapi: 3.1.0
info:
  title: API Game-score
  description: .
  version: 0.0.1

servers:
- url: http://localhost:7777
  description: Serveur de développement

tags:
  - name: hello
    description: première API avec Express
      
paths:
  /api/hello/world:
    get:
      tags:
        - hello
      description: message de bienvenue
      responses:
        200:
          description: retourne un message de bienvenue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/World'
  /api/hello/square/{number}:
    get:
      tags:
        - hello
      description: retourne le carré d'un nombre
      parameters:
        - name: number
          in: path
          description: nombre à mettre au carré
          required: true
          schema:
            type: integer
      responses:
        200:
          description: retourne le carré du nombre
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Square'
  /api/hello:
    get:
      tags:
        - hello
      description: message de bienvenue
      responses:
        200:
          description: retourne un message de bienvenue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
    post: 
      tags:
        - hello
      description: poste un message
      responses: 
        201:
          description: poste un message dans la base de données
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloPost' 
        400:
          description: Données invalides.
  /api/hello/{id}:
    get:
      tags:
        - hello
      description: retourne le message selon un id
      parameters:
        - name: id
          in: path
          description: id du message
          required: true
          schema:
            type: string
      responses:
        200:
          description: retourne le message selon un id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloId'
        404:
          description: Message non trouvé.
    delete:
      tags:
        - hello
      description: supprime le message selon un id
      parameters:
        - name: id
          in: path
          description: id du message
          required: true
          schema:
            type: string
      responses:
        200:
          description: supprime le message selon un id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloId'
        404:
          description: Message non trouvé.
  /api/player:
    get:
      tags:
        - player
      description: Renvoie tout les joueurs
      parameters:
        - in: path
          name: lastname
          description: Nom de famille du joueur
          required: false
        - in: path
          name: country
          description: Pays du joueur
          required: false
        - in: path
          name: tour
          description: Tour du joueur
      responses:
        200:
          description: Renvoie tout les joueurs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
components:
  schemas:
    World:
      type: object
      properties:
        message:
          type: string
      additionalProperties: false
      required:
        - message
    Square:
      type: object
      properties:
        square:
          type: integer
      additionalProperties: false
      required:
        - square
    Hello:
      type: object
      properties:
        message:
          type: string
      additionalProperties: false
      required:
        - message
    HelloPost:
      type: object
      properties:
        message:
          type: string
      additionalProperties: false
      required:
        - message
    HelloId:
      type: object
      properties:
        message:
          type: string
      additionalProperties: false
      required:
        - message
    Player:
      type: object
      properties:
        lastname:
          type: string
        firstname:
          type: string
        country: 
          type: string
        tour:
          type: integer
      additionalProperties: false

